export const SorularAnket = [
  {id:1,
soru:" Genel olarak düşündüğünüzde Şirketimizde çalışmaktan ne ölçüde memnunsunuz?"},
{id:2,
soru:"Bugün yeniden işe girecek olsanız, yine Şirketimizde çalışmak üzere başvurur muydunuz?"},
 {id:3,
soru:"Şirketin misyonu  ve vizyonu (varoluş nedeni / amacı) yaptığınız işe ne kadar değer katmaktadır ?"},
{id:4,
soru:" Çalıştığım ortamın şartları ne derece uygun  (sıcaklık, temizlik, gürültü, nem vb.)?"},
{id:5,  soru:" İş kıyafetleri ile kullanılan araç ve gereçler, çalışma ortamına uygun mu?"},
{id:6,
soru:" Soyunma - Giyinme odasının  genel durumu nasıl ?"},
{id:7,
 soru:"İş yapmak için gereken bilgilere kolayca ulaşılabiliniyor mu?"},
 {id:8,
    soru:" İşin gerektirdiği sorumluluk ve görevleri ne kadar yerine getiriyorsun?"},
{id:9,
soru:"  Kendini yaptığın işe uygun buluyormusun?"},  
{id:10,
    soru:" İşe girişte verilen oryantasyon eğitimi sizce nasıl ?"},  
]