export const Sorular = [
    {id:1,
    soru:"Universal Torna Başında Kullanılması Gereken Kişisel Koruyucu Donanım Hangisidir ?",
    a: "Koruyucu Eldiven",
    b: "Koruyucu Gözlük",
    c: "Kulaklık",
    d: "Baret",
    dogruCevap:"b",
    aciklama:"Universal Tornalarda koruyucu kapak zorunludur. Eskiden koruyucu olmayan tezgahlarda talaş yada parça fırlamasına karşın gözlük kullanılırdı."
},
{id:2,
    soru:"Aşağıdaki durumlardan hangisi iş kazası sayılmaz  ?",
    a: "Göze Çapak Kaçması",
    b: "İş Yerinde İntihar Girişiminde Bulunulması",
    c: "Öğle Yemeğinden Dolayı Zehirlenme",
    d: "Halk Otobüsü ile Giderken Oluşan Trafik Kazası",
    dogruCevap:"d",
    aciklama:"Kendi imkanlarınızla işyerine gittiğiniz takdirde Sgk'nın sorumluluğundan çıkarsınız. İş yerinde yaşanan her türlü vaka İş Kazası olarak nitelendirilir."
},
{id:3,
    soru:"Yükü kaldırırken asıl kullanılması gereken vücut bölümü hangisidir ?",
    a: "Sırt",
    b: "Kollar",
    c: "Bacak",
    d: "Bel",
    dogruCevap:"c",
    aciklama:"Vücut kas kütlesinin büyük kısmı bacaklardadır. Yükler bacak ile kaldırılmalı, bele yük verilmemelidir."
},
{id:4,
    soru:"Tehlike Rengi Hangisidir ?",
    a: "Mavi",
    b: "Yeşil",
    c: "Kırmızı",
    d: "Kahverengi",
    dogruCevap:"c",
    aciklama:"Tehlike kırmızı rengidir. Yeşil güvenli yer. Mavi zorunluluk."
},
{id:5,
    soru:"Ergonomiye Bağlı Başlıca Oluşan Hastalıklar Hangi Bölgede Meydana Gelir ?",
    a: "Bel",
    b: "Göz",
    c: "Kulak",
    d: "Mide",
    dogruCevap:"a",
    aciklama: "İnsan vücudu (iskelet sistemi ve kas sistemi) rahatsızlıklar Ergonomi Biliminde incelenir."
},
{id:6,
    soru:"Acil Ambulans Numarası Kaçtır ?",
    a: "112",
    b: "118",
    c: "119",
    d: "110",
    dogruCevap:"a",
    aciklama:"112'dir. 2021 öncesi itfaiye, polis, acil kurtarma gibi kurumların farklı numaraları vardı. Artık tek çatı altında 112 olarak kullanılmaktadır."
},
{id:7,
    soru:"Sınır üstünde gürültü çıkaran bir makinaya karşı alınacak ilk önlem hangisidir  ?",
    a: "Kulaklık Takmak",
    b: "Makineyi işletmenin uzak bir kısmına taşımak",
    c: "Makinenin ses çıkaran parçalarını değiştirmek",
    d: "Makinayı ses geçirmeyen bir bölüme almak.",
    dogruCevap:"c",
    aciklama:"İlk önceliğimiz her zaman makinede önlem almaktır. Yapılamadığı takdirde diğer önlemler alınır."
},
{id:8,
    soru:"Aşağıdakilerden hangisi elektrikten korunmak için kullanılan bir yöntemdir ?",
    a: "Çelik burunlu ayakkabı kullanımı",
    b: "İş Eldiveni Kullanımı",
    c: "Plastik Kaplı Pense Kullanımı",
    d: "Soğutucu Sıvı Kullanımı",
    dogruCevap:"c",
    aciklama:"Yalıtkan olarak plastik kullanılmaktadır."
},
{id:9,
    soru:"Boryağ yutan birine aşağıdakilerden hangisi yapılmaz ?",
    a: "Kusturulur",
    b: "Acil Ambulans aranır.",
    c: "Bor yağının MSDS’ine bakılır.",
    d: "Boryağından numune alınır.",
    dogruCevap:"a",
    aciklama:"Kimyasal yutan kişi hiçbir şekilde kusturulmaz. Çünkü mide, vücudun diğer organlarına göre çok daha fazla dayanıklıdır."
},
{id:10,
    soru:"Haftalık Yasal Çalışma Saati Ne kadardır ?",
    a: "40",
    b: "45",
    c: "52",
    d: "Belirli bir zaman yoktur.",
    dogruCevap:"b",
    aciklama:"45 Saattir. Haftalık 45 saati geçen sürelerde fazla mesai verilmektedir."
}
]